aws_access_key = ""
aws_secret_key = ""
aws_region = "eu-west-1"
aws_key = ""
aws_vpc = "vpc-1c5dee65"
aws_azs = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
aws_image_id = "ami-0d1bf5b68307103c2"
aws_clusterName = "eks-cluster"
aws_bucket_name = "snapshot-iypbshnfqgsg"
aws_instance_type = "m4.large"
aws_asg_max_size  = 5
aws_asg_min_size  = 3
aws_asg_desired_capacity = 3
